### PR TITLE
Feature events

### PR DESCRIPTION
**Pull request by stevenmukama**
###Highlights 

- [ ] Fixed linter errors
- [ ] Added required changes

### CODE REVIEW

**Comment by rloterh** [comment]
Hi @stevenmukama 
Looking at records of this activity from the dashboard, it seems like this project has been initially reviewed. Can you kindly inform why you're using a new Pull Request?

Cheers! 😃

**Comment by stevenmukama** [comment]
> 
I made a mistake i just forgot and created a new pull request but it is a mistake sorry

**Comment by stevenmukama** [comment]
i am sorry i just realized i made a mistake i opened  a new pull request

**Comment by rloterh** [comment]
Thanks for getting back soon @stevenmukama 

I also noticed that your PR title(_Feature events_) and project branch name does not correspond with the activity name (_Math magicians: components_) for which you submitted this project.

In this case, I'll send back the project to you so that you resubmit the this project using the initial Pull Request (Required) or resubmit under the correct name.

Cheers 😃

**Review by rloterh — COMMENTED** [review]
Hi Steven, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, using inconsistent Pull Requests. Kindly ensure to use the same Pull Request as the first time this activity was reviewed to request for another code review.

Otherwise, kindly ensure that your Pull Request title corresponds accordingly with the activity you submitted the project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by stevenmukama** [comment]
> 

okay let me do that

**Review by EricMbouwe — APPROVED** [review]
Hi @stevenmukama, 

Your project is complete! ⚡🔥  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Highlights 🎉🔥
- The project has an operate.js file ✔
- The project has a calculate.js file ✔
- The `Calculator` component imports the `calculate.js` file from the logic directory ✔
- Use of the state and props. ✔
- No linter errors ✔

## Optional suggestions ☂

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
